# Generated by Django 4.1 on 2022-11-16 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_member_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=255)),
                (
                    "user_group",
                    models.CharField(
                        choices=[
                            ("M", "Member State"),
                            ("O", "Organization"),
                            ("S", "SADC"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("A", "Administrator"), ("F", "Focal Point Person")],
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
    ]
