# Generated by Django 4.1 on 2022-11-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0016_delete_systemuser"),
        ("core", "0004_systemuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemuser",
            name="user_group",
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="user_type",
        ),
        migrations.AddField(
            model_name="systemuser",
            name="user_member_state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="portaldata.memberstate",
            ),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="user_organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="portaldata.organisation",
            ),
        ),
    ]
