# Generated by Django 4.1 on 2022-11-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0016_delete_systemuser"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0005_remove_systemuser_user_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="user_group",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="auth.group"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="user_member_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="portaldata.memberstate",
            ),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="user_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="portaldata.organisation",
            ),
        ),
    ]
