# Generated by Django 4.1 on 2022-11-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_systemuser_user_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemuser",
            old_name="user_organization",
            new_name="user_organisation",
        ),
    ]
