# Generated by Django 4.1 on 2022-11-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_user_organization_systemuser_user_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
