# Generated by Django 4.1 on 2023-02-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_systemuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Organisation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
