# Generated by Django 4.1 on 2023-02-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_user_organisation_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Organisation",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="systemuser",
            name="organisation_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="role",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
