# Generated by Django 4.1 on 2023-02-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_user_organisation_remove_user_role_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemuser",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
