# Generated by Django 4.1 on 2023-02-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0057_alter_assignedindicator_options_and_more"),
        ("core", "0011_rename_phone_systemuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="user_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="portaldata.organisation",
                verbose_name="Organisation",
            ),
        ),
    ]
