# Generated by Django 4.1 on 2023-02-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0059_generalindicator_series_name"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0012_alter_systemuser_user_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="user_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="auth.group",
                verbose_name="User Group",
            ),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="user_member_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="portaldata.memberstate",
                verbose_name="User Member State",
            ),
        ),
    ]
