# Generated by Django 4.1 on 2023-04-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="organisation_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Organisation Name"
            ),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
