# Generated by Django 4.1 on 2023-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FP", "Focal Point Person"),
                    ("DE", "Data Entry Person"),
                    ("SADC", "SADC Secretariat"),
                    ("SA", "System Admin"),
                ],
                max_length=150,
            ),
        ),
    ]
