# Generated by Django 4.1 on 2022-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatordata",
            name="value",
            field=models.TextField(blank=True, null=True, verbose_name="Data"),
        ),
    ]
