# Generated by Django 4.1 on 2022-11-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0002_alter_indicatordata_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicator",
            name="key",
        ),
        migrations.AddField(
            model_name="indicatordata",
            name="value_NA",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
