# Generated by Django 4.1 on 2022-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0003_remove_indicator_key_indicatordata_value_na"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporting_start_date", models.DateField()),
                ("reporting_end_date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="indicatordata",
            name="value_NA",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Data N/A"
            ),
        ),
    ]
