# Generated by Django 4.1 on 2022-11-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0004_reportingperiod_alter_indicatordata_value_na"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangeratedata",
            name="exchange_rate_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
