# Generated by Django 4.1 on 2022-11-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portaldata",
            "0006_alter_systemuser_options_remove_systemuser_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="memberstate",
            name="memberstate_status",
            field=models.BooleanField(
                choices=[(True, "Active"), (False, "Inactive")], default=True
            ),
        ),
    ]
