# Generated by Django 4.1 on 2022-11-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0008_remove_memberstate_memberstate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberstate",
            name="memberstate_status",
            field=models.BooleanField(
                choices=[(True, "Active"), (False, "Inactive")], default=True
            ),
        ),
    ]
