# Generated by Django 4.1 on 2022-11-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0009_memberstate_memberstate_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exchangeratedata",
            options={"verbose_name_plural": "Exchange Rate Data"},
        ),
        migrations.AlterModelOptions(
            name="indicatordata",
            options={"verbose_name_plural": "Indicator Data"},
        ),
        migrations.AlterModelOptions(
            name="reportingperiod",
            options={"verbose_name_plural": "Reporting Period"},
        ),
        migrations.AddField(
            model_name="indicator",
            name="indicator_assigned_to",
            field=models.CharField(
                choices=[("M", "Member State"), ("O", "Organization"), ("S", "SADC")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
