# Generated by Django 4.1 on 2022-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0010_alter_exchangeratedata_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="indicator_assigned_to",
            field=models.CharField(
                choices=[("M", "Member States"), ("O", "Organizations"), ("S", "SADC")],
                max_length=1,
            ),
        ),
    ]
