# Generated by Django 4.1 on 2022-11-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0011_alter_indicator_indicator_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="focusarea",
            name="focusarea_status",
            field=models.BooleanField(
                choices=[(True, "Active"), (False, "Inactive")], default=True
            ),
        ),
    ]
