# Generated by Django 4.1 on 2022-11-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0013_memberstate_member_state_short_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
        migrations.AlterField(
            model_name="organisation",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
