# Generated by Django 4.1 on 2022-11-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0018_assignedindicator_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="organisation_status",
            field=models.BooleanField(
                choices=[(True, "Active"), (False, "Inactive")], default=True
            ),
        ),
        migrations.AlterField(
            model_name="assignedindicator",
            name="assigned_to_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portaldata.organisation",
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="assignedindicator",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portaldata.indicator"
            ),
        ),
    ]
