# Generated by Django 4.1 on 2022-11-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0020_exchangeratedata_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangeratedata",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="exchangeratedata",
            name="created_date",
        ),
    ]
