# Generated by Django 4.1 on 2022-11-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0021_remove_exchangeratedata_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangeratedata",
            name="member_state",
        ),
        migrations.AddField(
            model_name="currency",
            name="currency_short_name",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
