# Generated by Django 4.1 on 2022-11-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0022_remove_exchangeratedata_member_state_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exchangeratedata",
            unique_together={("reporting_year", "currency")},
        ),
    ]
