# Generated by Django 4.1 on 2022-11-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0023_alter_exchangeratedata_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="member_state",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="portaldata.memberstate"
            ),
        ),
    ]
