# Generated by Django 4.1 on 2022-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0024_alter_currency_member_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicatordata",
            name="validated",
        ),
        migrations.AddField(
            model_name="indicatordata",
            name="validation_status",
            field=models.IntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Ready for validation"),
                    (3, "Returned for revision"),
                    (4, "Validated"),
                ],
                default=1,
            ),
        ),
    ]
