# Generated by Django 4.1 on 2022-11-22 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portaldata", "0025_remove_indicatordata_validated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorDataValidationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_data", models.CharField(max_length=200)),
                ("current", models.BooleanField(default=True)),
                ("comments", models.TextField(blank=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "indicator_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portaldata.indicatordata",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="revision_last_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_update"],
            },
        ),
    ]
