# Generated by Django 4.1 on 2022-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0026_indicatordatavalidationhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatordatavalidationhistory",
            name="current",
            field=models.BooleanField(default=False),
        ),
    ]
