# Generated by Django 4.1 on 2022-11-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0027_alter_indicatordatavalidationhistory_current"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indicatordata",
            old_name="value",
            new_name="ind_value",
        ),
    ]
