# Generated by Django 4.1 on 2022-12-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0028_rename_value_indicatordata_ind_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatordata",
            name="ind_value_usd",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
    ]
