# Generated by Django 4.1 on 2022-12-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0029_indicatordata_ind_value_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatordata",
            name="ind_value_adjusted",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
