# Generated by Django 4.1 on 2022-12-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0031_remove_indicatordata_ind_value_usd"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicatordata",
            options={
                "ordering": ["member_state", "-reporting_year", "indicator"],
                "verbose_name_plural": "Indicator Data",
            },
        ),
        migrations.AlterField(
            model_name="indicatordata",
            name="ind_value_adjusted",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Data adjusted"
            ),
        ),
    ]
