# Generated by Django 4.1 on 2022-12-17 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portaldata", "0033_alter_indicatordatavalidationhistory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalindicator",
            name="indicator_value",
        ),
        migrations.RemoveField(
            model_name="generalindicator",
            name="reporting_year",
        ),
        migrations.CreateModel(
            name="GeneralIndicatorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indicator_value", models.CharField(max_length=200)),
                ("reporting_year", models.CharField(max_length=6)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "general_indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="portaldata.generalindicator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="GeneralIndicatorData_Last_Updated_By",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
