# Generated by Django 4.1 on 2022-12-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0035_generalindicator_definition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generalindicatordata",
            options={"verbose_name_plural": "General Indicator Data"},
        ),
        migrations.AlterField(
            model_name="generalindicator",
            name="indicator_label",
            field=models.CharField(max_length=200, verbose_name="Indicator"),
        ),
        migrations.AlterField(
            model_name="generalindicatordata",
            name="general_indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="portaldata.generalindicator",
                verbose_name="Indicator",
            ),
        ),
        migrations.AlterField(
            model_name="generalindicatordata",
            name="indicator_value",
            field=models.CharField(max_length=200, verbose_name="Data"),
        ),
        migrations.AlterUniqueTogether(
            name="generalindicatordata",
            unique_together={("general_indicator", "reporting_year")},
        ),
    ]
