# Generated by Django 4.1 on 2022-12-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0036_alter_generalindicatordata_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="generalindicatordata",
            unique_together=set(),
        ),
    ]
