# Generated by Django 4.1 on 2022-12-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0038_alter_generalindicatordata_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportingperiod",
            options={
                "ordering": ["-reporting_end_date"],
                "verbose_name_plural": "Reporting Period",
            },
        ),
        migrations.AddField(
            model_name="reportingperiod",
            name="current",
            field=models.BooleanField(default=False),
        ),
    ]
