# Generated by Django 4.1 on 2023-01-02 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portaldata", "0039_alter_reportingperiod_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ["member_state"], "verbose_name_plural": "Currencies"},
        ),
        migrations.AlterModelOptions(
            name="exchangeratedata",
            options={
                "ordering": ["-reporting_year", "currency__member_state"],
                "verbose_name_plural": "Exchange Rate Data",
            },
        ),
        migrations.AlterModelOptions(
            name="indicatordata",
            options={
                "ordering": ["-reporting_year", "member_state", "indicator"],
                "verbose_name_plural": "Indicator Data",
            },
        ),
        migrations.CreateModel(
            name="Published",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporting_year", models.CharField(max_length=6, unique=True)),
                (
                    "published_status",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        verbose_name="Is Published ? ",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="PublishedYear_Last_Updated_By",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Published",
            },
        ),
    ]
