# Generated by Django 4.1 on 2023-01-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0040_alter_currency_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="published",
            options={
                "ordering": ["-reporting_year"],
                "verbose_name_plural": "Published",
            },
        ),
        migrations.CreateModel(
            name="IndicatorChartConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chart_title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            (0, "Column Chart"),
                            (1, "Line Chart"),
                            (2, "Stacked Column Chart"),
                            (3, "Spiderweb Chart"),
                            (4, "Sunburst Chart"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "aggregated",
                    models.CharField(
                        blank=True,
                        choices=[("avg", "Average"), ("sum", "Total")],
                        max_length=10,
                    ),
                ),
                ("indicators_list", models.ManyToManyField(to="portaldata.indicator")),
            ],
            options={
                "verbose_name_plural": "Indicator Data Configurations",
            },
        ),
    ]
