# Generated by Django 4.1 on 2023-01-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0041_alter_published_options_indicatorchartconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicatorchartconfig",
            options={"verbose_name_plural": "Indicator Chart Configurations"},
        ),
    ]
