# Generated by Django 4.1 on 2023-01-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0042_alter_indicatorchartconfig_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorchartconfig",
            name="chart_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Column Chart"),
                    (1, "Line Chart"),
                    (2, "Stacked Column Chart"),
                    (3, "Spiderweb Chart"),
                    (4, "Sunburst Chart"),
                ]
            ),
        ),
    ]
