# Generated by Django 4.1 on 2023-01-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0043_alter_indicatorchartconfig_chart_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indicatorchartconfig",
            old_name="aggregated",
            new_name="aggregation",
        ),
        migrations.CreateModel(
            name="IndicatorScoreCardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scorecard_title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "aggregation",
                    models.CharField(
                        blank=True,
                        choices=[("avg", "Average"), ("sum", "Total")],
                        max_length=10,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portaldata.indicator",
                        verbose_name="Indicator",
                    ),
                ),
            ],
        ),
    ]
