# Generated by Django 4.1 on 2023-01-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portaldata",
            "0044_rename_aggregated_indicatorchartconfig_aggregation_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicatorchartconfig",
            options={"verbose_name_plural": "Indicator Chart Configuration"},
        ),
        migrations.AlterModelOptions(
            name="indicatorscorecardconfig",
            options={"verbose_name_plural": "Indicator Scorecard Configuration"},
        ),
        migrations.AddField(
            model_name="indicatorchartconfig",
            name="y_axis_title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
