# Generated by Django 4.1 on 2023-02-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0047_alter_indicator_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IndicatorChartConfig",
            new_name="Charts",
        ),
    ]
