# Generated by Django 4.1 on 2023-02-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0049_rename_charts_chart_alter_chart_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chart",
        ),
    ]
