# Generated by Django 4.1 on 2023-02-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0051_chart_indicatorchartconfig_chart_indicators_list"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IndicatorChartConfig",
            new_name="ChartConfig",
        ),
        migrations.AlterModelOptions(
            name="chartconfig",
            options={"verbose_name_plural": "Chart Configuration"},
        ),
    ]
