# Generated by Django 4.1 on 2023-02-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0052_rename_indicatorchartconfig_chartconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="chart_name",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
    ]
