# Generated by Django 4.1 on 2023-02-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0053_chart_chart_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chart",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="chartconfig",
            options={
                "ordering": ["chart__pk"],
                "verbose_name_plural": "Chart Configuration",
            },
        ),
        migrations.AddField(
            model_name="chartconfig",
            name="series_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="chartconfig",
            name="extra_calculation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("per100", "Calculate Per 100"),
                    ("exchangerate", "Convert Currency to USD"),
                    ("mainstack", "Main Group in Stacked Chart"),
                ],
                max_length=50,
            ),
        ),
    ]
