# Generated by Django 4.1 on 2023-02-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0054_alter_chart_options_alter_chartconfig_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="aggregation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("avg", "Average"),
                    ("sum", "Total"),
                    ("yesPercentage", "Percent of Yes answers"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="chartconfig",
            name="extra_calculation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("per100", "Calculate Per 100"),
                    ("exchangerate", "Convert Currency to USD"),
                    ("mainstack", "Main Group in Stacked Chart"),
                    ("yesPercentage", "Calculate Yes percentage"),
                ],
                max_length=50,
            ),
        ),
    ]
