# Generated by Django 4.1 on 2023-02-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0055_alter_chart_aggregation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chartconfig",
            options={
                "ordering": ["chart__pk", "pk"],
                "verbose_name_plural": "Chart Configuration",
            },
        ),
    ]
