# Generated by Django 4.1 on 2023-02-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0056_alter_chartconfig_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignedindicator",
            options={"verbose_name_plural": "Assigned Indicators"},
        ),
        migrations.AlterModelOptions(
            name="focusarea",
            options={"ordering": ["sn"], "verbose_name_plural": "Focus Areas"},
        ),
        migrations.AlterModelOptions(
            name="memberstate",
            options={
                "ordering": ["member_state"],
                "verbose_name_plural": "Member States",
            },
        ),
        migrations.AlterModelOptions(
            name="reportingperiod",
            options={
                "ordering": ["-reporting_end_date"],
                "verbose_name_plural": "Reporting Periods",
            },
        ),
        migrations.AddField(
            model_name="indicator",
            name="type_of_currency",
            field=models.CharField(
                blank=True,
                choices=[("usd", "USD"), ("local", "Local Currency")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chartconfig",
            name="extra_calculation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("per100", "Calculate Per 100"),
                    ("exchangerate", "Convert Currency to USD"),
                    ("mainstack", "Main Group in Stacked Chart"),
                    ("yesPercentage", "Calculate Yes percentage"),
                    ("mtokbits", "Covert Mbits to Kbits"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="memberstate",
            name="member_state",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Memeber State"
            ),
        ),
    ]
