# Generated by Django 4.1 on 2023-02-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0057_alter_assignedindicator_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalindicator",
            name="include_in_chart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="portaldata.chart",
            ),
        ),
    ]
