# Generated by Django 4.1 on 2023-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0058_generalindicator_include_in_chart"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalindicator",
            name="series_name",
            field=models.CharField(
                blank=True,
                help_text="If part of a chart, enter the series name. Otherwise the full Indicator Name will be used.",
                max_length=50,
                null=True,
            ),
        ),
    ]
