# Generated by Django 4.1 on 2023-04-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0060_alter_reportingperiod_reporting_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="focusarea",
            options={
                "ordering": ["sn"],
                "verbose_name": "Focus Area",
                "verbose_name_plural": "Focus Areas",
            },
        ),
        migrations.AlterModelOptions(
            name="generalindicator",
            options={"verbose_name": "General Indicator"},
        ),
    ]
