# Generated by Django 4.1 on 2023-04-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0061_alter_focusarea_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="data_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Currency"),
                    (1, "Whole Number"),
                    (2, "Decimal"),
                    (3, "Percentage"),
                    (4, "Text"),
                    (5, "Select (Yes/No)"),
                    (6, "Text Area"),
                    (7, "URL"),
                    (8, "Email"),
                    (9, "Date"),
                ],
                verbose_name="Data Type",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="focus_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="portaldata.focusarea",
                verbose_name="Focus Area",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="indicator_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Indicator Number"
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="indicator_type",
            field=models.CharField(
                choices=[("Core", "Core"), ("Extended", "Extended")],
                default="Core",
                max_length=8,
                verbose_name="Indicator Type",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Archived", "Archived")],
                default="Active",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="indicatordata",
            name="ind_value_adjusted",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Data Converted (local currency data converted to USD)",
            ),
        ),
        migrations.AlterField(
            model_name="indicatordata",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="portaldata.indicator",
                verbose_name="Indicator",
            ),
        ),
        migrations.AlterField(
            model_name="indicatordata",
            name="member_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="portaldata.memberstate",
                verbose_name="Member State",
            ),
        ),
        migrations.AlterField(
            model_name="indicatordata",
            name="reporting_year",
            field=models.CharField(max_length=6, verbose_name="Reporting Year"),
        ),
    ]
