# Generated by Django 4.1 on 2023-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0064_scorecard_scorecardconfig_scorecard_indicator_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorecardconfig",
            name="aggregation",
            field=models.CharField(
                blank=True,
                choices=[("avg", "Average"), ("sum", "Total")],
                max_length=50,
            ),
        ),
    ]
