# Generated by Django 4.1 on 2023-04-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaldata", "0065_scorecardconfig_aggregation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scorecardconfig",
            old_name="extra_calculation",
            new_name="num_denom",
        ),
    ]
