# Generated by Django 4.1 on 2025-08-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaldata', '0070_alter_memberstate_member_state_iso3_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberstate',
            name='member_state',
            field=models.CharField(max_length=255, unique=True, verbose_name='Member State'),
        ),
    ]
